import { createVueConfig } from '@arxhub/toolchain-vite'
import { defineConfig } from 'vite'

export default defineConfig((env) =>
  createVueConfig(__dirname, env, {
    entries: ['src/ui.ts'],
    // Exact subpaths keep extension constructors and UI singletons owned by their peer packages.
    external: [
      '@arxhub/core',
      '@arxhub/plugin-sync/ui',
      '@arxhub/sync',
      '@arxhub/crypto',
      '@arxhub/plugin-protection/ui',
      '@arxhub/plugin-publish/ui',
      '@arxhub/errors',
      '@arxhub/stdlib/collections/container',
      '@arxhub/stdlib/scheduling/debounced-task',
      '@arxhub/path',
      '@arxhub/plugin-explorer/ui',
      '@arxhub/plugin-hotkeys/ui',
      '@arxhub/plugin-notes/ui',
      '@arxhub/plugin-shell/ui',
      '@arxhub/plugin-panels/ui',
      '@arxhub/plugin-search/ui',
      '@arxhub/uikit/core',
      '@arxhub/uikit/hooks',
      '@arxhub/vfs',
      'prosemirror-model',
      'prosemirror-state',
      'prosemirror-view',
      'prosemirror-commands',
      'prosemirror-history',
      'prosemirror-inputrules',
      'prosemirror-keymap',
      'prosemirror-schema-basic',
      'prosemirror-schema-list',
      'prosemirror-tables',
      '@codemirror/language',
      '@codemirror/language-data',
      '@lezer/highlight',
      'mdast-util-from-markdown',
      'mdast-util-gfm',
      'micromark-extension-gfm',
      'vue',
    ],
  }),
)
