import { expect, openNavigation, test } from './fixtures'

const document = (...texts: string[]) =>
  JSON.stringify({ version: 1, doc: { type: 'doc', content: texts.map((text) => ({ type: 'paragraph', content: [{ type: 'text', text }] })) } })

test('internal block links persist, open through Notes and appear as backlinks', async ({ app, vault }) => {
  const target = await vault.write(`${test.info().project.name}-destination.arx`, document('First block', 'Chosen destination'))
  const source = await vault.write(`${test.info().project.name}-source.arx`, document('Visit destination'))
  await app.reload()
  await openNavigation(app)
  await app.getByRole('treeitem', { name: source, exact: true }).click()
  const editor = app.locator('.ProseMirror:visible')
  await expect(editor).toContainText('Visit destination')
  await editor.locator('p').click()
  await app.keyboard.press('Home')
  await app.keyboard.press('Shift+End')
  const more = app.getByRole('button', { name: 'More formatting', exact: true })
  if (await more.isVisible()) {
    await more.click()
    await app.getByRole('menuitem', { name: 'Link', exact: true }).click()
  } else await app.getByRole('button', { name: 'Link', exact: true }).click()
  const dialog = app.getByRole('dialog', { name: 'Link', exact: true })
  await dialog.getByRole('button', { name: 'Choose document or block' }).click()
  await dialog.getByRole('textbox', { name: 'Search link destinations' }).fill(target)
  await dialog.getByRole('button', { name: new RegExp(target.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) }).click()
  await dialog.getByRole('button', { name: 'Chosen destination', exact: true }).click()
  await expect(dialog.getByRole('textbox', { name: 'Link address' })).toHaveValue(/#text=Chosen/)
  await dialog.getByRole('button', { name: 'Apply link', exact: true }).click()
  await app.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => vault.read(source)).toContain('#text=Chosen')
  await app.getByRole('button', { name: /^Editor mode:/ }).click()
  await app.getByRole('menuitem', { name: 'Read only', exact: true }).click()
  await expect(editor).toBeFocused()
  await editor.getByRole('link', { name: 'Visit destination' }).click()
  await expect(editor).toContainText('Chosen destination')
  await expect.poll(() => editor.evaluate(() => window.getSelection()?.toString())).toBe('Chosen destination')
  await app.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await app.getByRole('button', { name: 'Document tools', exact: true }).click()
  await app.getByRole('menuitem', { name: 'Copy link to block', exact: true }).click()
  await expect.poll(() => app.evaluate(() => navigator.clipboard.readText())).toContain('#text=Chosen')
  await app.getByRole('button', { name: 'Document tools', exact: true }).click()
  await app.getByRole('menuitem', { name: 'Backlinks', exact: true }).click()
  const backlinks = app.getByRole('dialog', { name: 'Backlinks', exact: true })
  await expect(backlinks.getByRole('button', { name: new RegExp(source.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) })).toBeVisible({
    timeout: 15_000,
  })
  await backlinks.getByRole('button', { name: new RegExp(source.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) }).click()
  await expect(editor).toContainText('Visit destination')
  await expect(editor.getByRole('link', { name: 'Visit destination' })).toHaveAttribute('href', /#text=Chosen/)
  const saved = JSON.parse(await vault.read(target))
  saved.doc.content[1].content[0].text = 'Renamed and edited destination'
  const renamed = await vault.write(`${test.info().project.name}-renamed.arx`, JSON.stringify(saved))
  await vault.remove(target)
  await app.reload()
  await openNavigation(app)
  await app.getByRole('treeitem', { name: source, exact: true }).click()
  await app.getByRole('button', { name: /^Editor mode:/ }).click()
  await app.getByRole('menuitem', { name: 'Read only', exact: true }).click()
  await editor.getByRole('link', { name: 'Visit destination' }).click()
  await expect(editor).toContainText('Renamed and edited destination')
  await expect.poll(() => editor.evaluate(() => window.getSelection()?.toString())).toBe('Renamed and edited destination')
  expect(await vault.read(renamed)).toContain(saved.documentId)
})
