import { expect, isMobileFrame, openNavigation, openNote, openSearchApp, openType, searchSheet, test, typeKey } from './fixtures'

const arx = (text: string) =>
  JSON.stringify({ version: 1, doc: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text }] }] } })

test('a search snippet selects its text on first and repeated opening', async ({ app, vault }) => {
  for (const extension of ['md', 'arx']) {
    const text = `Find the unique${extension}needle in this paragraph.`
    await vault.write(`anchor.${extension}`, extension === 'arx' ? arx(text) : text)
    await app.reload()
    for (let opening = 0; opening < 2; opening++) {
      await openSearchApp(app)
      await app.getByRole('textbox', { name: 'Search', exact: true }).fill(`unique${extension}needle`)
      const snippet = app.getByRole('option').filter({ hasText: text })
      await expect(snippet).toBeVisible()
      await snippet.click()
      await expect(typeKey(app, 'Notes')).toHaveAttribute('aria-pressed', 'true')
      await expect.poll(() => app.evaluate(() => window.getSelection()?.toString())).toBe(`unique${extension}needle`)
      await app.keyboard.press('ArrowRight')
    }
  }
})

test('renaming an open document preserves its buffer and saves to the new path', async ({ app, vault }) => {
  const path = await vault.write(`${test.info().project.name}-rename.md`, 'original\n')
  await openNote(app, path)
  await app.locator('.cm-line').first().click()
  await app.keyboard.press('End')
  await app.keyboard.insertText(' edited')
  await openNavigation(app)
  await app.getByRole('treeitem', { name: path, exact: true }).click({ button: 'right' })
  await app.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  const renamed = path.replace('.md', '-renamed.md')
  const input = app.getByRole('textbox', { name: 'New name', exact: true })
  await input.fill(renamed)
  await input.press('Enter')
  await expect(app.getByRole('treeitem', { name: renamed, exact: true })).toBeVisible()
  await app.getByRole('treeitem', { name: renamed, exact: true }).click()
  await expect(app.locator('.cm-content')).toHaveCount(1)
  await expect(app.locator('.cm-content')).toContainText('original edited')
  await app.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => vault.read(renamed)).toContain('original edited')
  expect(await vault.read(path).catch(() => null)).toBeNull()
  await app.reload()
  await expect(app.locator('.cm-content')).toContainText('original edited')
})

test('creating repeatedly keeps the earlier notes and opens the new one', async ({ app, vault }) => {
  const original = arx('Keep this note')
  const path = await vault.write(`${test.info().project.name}-folder/untitled.arx`, original)
  const folder = path.slice(0, path.lastIndexOf('/'))
  await app.reload()
  await openNavigation(app)
  await app.getByRole('treeitem', { name: folder, exact: true }).click()
  await app.getByRole('button', { name: 'New file', exact: true }).click()
  await app.getByRole('menuitem', { name: 'New document', exact: true }).click()
  await expect(app.locator('.ProseMirror:visible')).toBeVisible()
  await app.locator('.ProseMirror:visible').fill('Second note')
  await app.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => vault.read(`${folder}/untitled 2.arx`)).toContain('Second note')
  await openNavigation(app)
  await app.getByRole('button', { name: 'New file', exact: true }).click()
  await app.getByRole('menuitem', { name: 'New document', exact: true }).click()
  await expect.poll(() => vault.read(`${folder}/untitled 3.arx`).catch(() => '')).toContain('paragraph')
  expect(await vault.read(path)).toBe(original)
  expect(await vault.read(`${folder}/untitled 2.arx`)).toContain('Second note')
})

test('search returns to the same buffer and keeps its query', async ({ app, vault }) => {
  const path = await vault.write('single-buffer.md', 'original needle\n')
  await openNote(app, path)
  const editor = app.locator('.cm-content:visible')
  await editor.click()
  await app.keyboard.press('ControlOrMeta+End')
  await app.keyboard.insertText(' from-notes')
  await app.getByRole('button', { name: 'Save', exact: true }).click()
  await openSearchApp(app)
  const query = app.getByRole('textbox', { name: 'Search', exact: true })
  await query.fill('needle')
  const result = app.getByRole('option').filter({ hasText: path })
  await expect(result).toBeVisible()
  await result.click()
  await expect(typeKey(app, 'Notes')).toHaveAttribute('aria-pressed', 'true')
  await expect(app.locator('.cm-content')).toHaveCount(1)
  await expect(editor).toContainText('from-notes')
  await editor.click()
  await app.keyboard.press('ControlOrMeta+End')
  await app.keyboard.insertText(' from-search')
  await app.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => vault.read(path)).toContain('from-notes from-search')
  await openSearchApp(app)
  await expect(query).toHaveValue('needle')
})

test('folders stay expanded after switching types and restarting', async ({ app, vault }) => {
  const path = await vault.write('folder/child.md', 'child\n')
  const folder = path.split('/')[0]
  await app.reload()
  await openNavigation(app)
  await app.getByRole('treeitem', { name: folder, exact: true }).click()
  await openType(app, 'Settings')
  await openType(app, 'Notes')
  await openNavigation(app)
  await expect(app.getByRole('treeitem', { name: 'child.md', exact: true })).toBeVisible()
  await app.reload()
  await openNavigation(app)
  await expect(app.getByRole('treeitem', { name: 'child.md', exact: true })).toBeVisible()
  await app.getByRole('button', { name: 'Collapse tree' }).click()
  await expect(app.getByRole('treeitem', { name: folder, exact: true })).toHaveAttribute('aria-expanded', 'false')
})

test('the switcher traps focus and returns it to its opener', async ({ app, vault }) => {
  const path = await vault.write('focus.md', 'continue typing here\n')
  await openNote(app, path)
  const editor = app.locator('.cm-content:visible')
  await editor.click()
  await app.keyboard.press('ControlOrMeta+k')
  const sheet = searchSheet(app)
  await expect(sheet).toBeVisible()
  for (let n = 0; n < 16; n++) {
    await app.keyboard.press(n < 8 ? 'Tab' : 'Shift+Tab')
    expect(await sheet.evaluate((el) => el.contains(document.activeElement))).toBe(true)
  }
  await app.keyboard.press('Escape')
  await expect(sheet).toBeHidden()
  await expect(editor).toBeFocused()
  const trigger = app.getByRole('button', { name: 'Open or switch to', exact: true })
  await trigger.click()
  await expect(sheet).toBeVisible()
  await expect(sheet.locator('button.row').first()).toBeFocused()
  await app.keyboard.press('Escape')
  await expect(sheet).toBeHidden()
  await expect(trigger).toBeFocused()
})

test('an unpinned tool can be closed and stays closed after restart', async ({ app }) => {
  await openSearchApp(app)
  await app.getByRole('button', { name: 'Open or switch to', exact: true }).click()
  await searchSheet(app).getByRole('button', { name: 'Close Search', exact: true }).click()
  await app.keyboard.press('Escape')
  await expect(typeKey(app, 'Search')).toHaveCount(0)
  await expect(typeKey(app, 'Notes')).toHaveAttribute('aria-pressed', 'true')
  await app.reload()
  await expect(typeKey(app, 'Search')).toHaveCount(0)
  await expect(typeKey(app, 'Notes')).toHaveAttribute('aria-pressed', 'true')
})

test('a missing restored document stays visible as gone instead of an empty editor', async ({ app, vault }) => {
  const path = await vault.write(`${test.info().project.name}-gone.md`, 'never recreate this file\n')
  await openNote(app, path)
  await vault.remove(path)
  await app.reload()
  await expect(app.getByText('This object is gone', { exact: true })).toBeVisible()
  await expect(app.locator('.cm-content')).toHaveCount(0)
  await app.getByTestId('object-gone-close').click()
  await app.reload()
  await expect(app.getByText('This object is gone', { exact: true })).toHaveCount(0)
})

test('splitting moves the live editor with its unsaved text and undo', async ({ app, vault }) => {
  test.skip(await isMobileFrame(app), 'desktop tiling')
  const path = await vault.write('split.md', 'original\n')
  await openNote(app, path)
  await app.locator('.cm-line').first().click()
  await app.keyboard.press('End')
  await app.keyboard.insertText(' unsaved')
  await app.getByRole('button', { name: 'Split right', exact: true }).click()
  await expect(app.locator('.panel-group-view')).toHaveCount(2)
  await expect(app.locator('.cm-content')).toHaveCount(1)
  await expect(app.locator('.cm-content:visible')).toContainText('original unsaved')
  await app.locator('.cm-line').first().click()
  await app.keyboard.press('ControlOrMeta+z')
  await expect(app.locator('.cm-content:visible')).not.toContainText('unsaved')
})

test('the mobile close control receives the actual touch', async ({ app, vault }) => {
  test.skip(!(await isMobileFrame(app)), 'touch target')
  const path = await vault.write('touch.md', 'touch me\n')
  await openNote(app, path)
  await app.setViewportSize({ width: 360, height: 640 })
  const close = app.getByRole('button', { name: 'Close document', exact: true })
  const box = await close.boundingBox()
  expect(box).not.toBeNull()
  if (box == null) return
  expect(box.width).toBeGreaterThanOrEqual(40)
  expect(box.height).toBeGreaterThanOrEqual(40)
  await app.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2)
  await expect(app.locator('.cm-content')).toHaveCount(0)
  await expect(app.getByRole('menu', { name: 'Open documents' })).toBeHidden()
})
