import { expect, isMobileFrame, openNavigation, openSettingsSection, test } from './fixtures'

test('file tree keyboard navigation loads folders and leaves inline editing in control', async ({ app, vault }) => {
  test.skip(await isMobileFrame(app), 'desktop keyboard')
  const path = await vault.write('folder/child.txt', 'preserve me')
  const folder = path.split('/')[0]!
  await app.reload()
  await openNavigation(app)
  const tree = app.getByRole('tree', { name: 'Files', exact: true })
  const branch = tree.getByRole('treeitem', { name: folder, exact: true })
  await branch.focus()
  await app.keyboard.press('ArrowRight')
  await expect(branch).toHaveAttribute('aria-expanded', 'true')
  const child = tree.getByRole('treeitem', { name: 'child.txt', exact: true })
  await expect(child).toBeVisible()
  await app.keyboard.press('ArrowRight')
  await expect(child).toBeFocused()
  await expect(child).toHaveAttribute('aria-level', '2')
  await expect(tree.locator('[role="treeitem"][tabindex="0"]')).toHaveCount(1)
  await app.keyboard.press('ArrowLeft')
  await expect(branch).toBeFocused()
  await app.keyboard.press('ArrowLeft')
  await expect(child).toBeHidden()
  await app.keyboard.press('ArrowRight')
  await expect(child).toBeVisible()
  await app.keyboard.press('ArrowRight')
  await expect(child).toBeFocused()
  await app.keyboard.press('F2')
  const input = app.getByRole('textbox', { name: 'New name', exact: true })
  await expect(input).toBeFocused()
  await input.fill('renamed')
  await app.keyboard.press('ArrowLeft')
  await expect(input).toBeFocused()
  expect(await input.evaluate((element: HTMLInputElement) => element.selectionStart)).toBe(6)
  await input.press('Enter')
  await expect(tree.getByRole('treeitem', { name: 'renamed.txt', exact: true })).toBeVisible()
  await expect.poll(() => vault.read(`${folder}/renamed.txt`).catch(() => null)).toBe('preserve me')
})

test('settings uses the same rows as the file tree without an expander column', async ({ app, vault }) => {
  const path = await vault.write('geometry.txt', 'body')
  await app.reload()
  await openNavigation(app)
  const file = app.getByRole('tree', { name: 'Files', exact: true }).getByRole('treeitem', { name: path, exact: true })
  const geometry = await file.evaluate((node) => {
    const style = getComputedStyle(node)
    return { height: node.getBoundingClientRect().height, font: style.fontFamily, size: style.fontSize, inset: style.paddingLeft }
  })
  await openSettingsSection(app, 'Appearance')
  await openNavigation(app)
  const settings = app.getByRole('tree', { name: 'Settings sections', exact: true })
  const appearance = settings.getByRole('treeitem', { name: 'Appearance', exact: true })
  await expect(appearance).toHaveAttribute('aria-selected', 'true')
  await expect(appearance).toHaveCSS('font-family', geometry.font)
  await expect(appearance).toHaveCSS('font-size', geometry.size)
  await expect(appearance).toHaveCSS('padding-left', geometry.inset)
  expect((await appearance.boundingBox())!.height).toBe(geometry.height)
  await expect(appearance).not.toHaveAttribute('aria-expanded')
  expect((await settings.getByRole('treeitem').first().boundingBox())!.y).toBe((await settings.boundingBox())!.y)
  if (!(await isMobileFrame(app))) {
    await appearance.focus()
    await app.keyboard.press('ArrowDown')
    const storage = settings.getByRole('treeitem', { name: 'Storage', exact: true })
    await expect(storage).toBeFocused()
    await expect(appearance).toHaveAttribute('aria-selected', 'true')
    await app.keyboard.press('Enter')
    await expect(storage).toHaveAttribute('aria-selected', 'true')
  }
})
