packages:
  - boot
  - toolchains/*
  - packages/*
  - plugins/*

catalogs:
  client:
    '@radix-ui/colors': ^3.0.0
  server:
    '@elysiajs/node': ^1.2.6
    elysia: ^1.2.25
    esbuild: ^0.25.2
  shared:
    '@signaldb/core': ^1.6.0
    async-lock: ^1.4.1
    memoirist: ^0.3.0
    nanoid: ^5.1.5
    ts-dedent: ^2.2.0
    rabin-rs: ^2.1.0
    fflate: ^0.8.2
    dayjs: ^1.11.18
    path-browserify: ^1.0.1
    crypto-browserify: ^3.12.1
  toolchain:
    '@biomejs/biome': ^2.2.6
    '@types/async-lock': ^1.4.2
    '@types/node': ^22.14.1
    '@types/pouchdb-adapter-memory': ^6.1.6
    '@types/pouchdb-core': ^7.0.15
    '@types/pouchdb-find': ^7.3.3
    glob: ^11.0.3
    rollup-plugin-node-externals: ^8.0.0
    type-fest: ^4.40.0
    typescript: ^5.9.3
    vite: ^7.1.10
    vite-node: ^3.2.4
    vite-plugin-dts: ^4.5.3
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - leveldown
