export { alignBlocks, alignLines, type SideCell, type SideRow } from './align'
export { DIFF_LAYER, DIFF_NEXT_CHANGE, DIFF_PREVIOUS_CHANGE } from './contributions'
export { DEFAULT_DIFF_SETTINGS, type DiffConfig, DiffConfigSchema, type DiffSettings, toDiffSettings } from './diff-config'
export { type AttachedDiffView, DiffExtension } from './diff-extension'
export { DiffPlugin } from './diff-plugin'
export type { DiffContext, DifferRegistration, DiffRequest, DiffSide } from './differ'
export { type FoldEntry, type FoldOptions, foldRuns } from './fold'
export type * from './model'
export { diffSequence, type SequenceOp } from './sequence'
export { countsOf, pluralRu, stopsOf } from './stops'
export { collapsedCount } from './strip-collapse'
export { replacedModel, textDiff } from './text-differ'
export { decodeText, wordDiff } from './word-diff'
