export { default as ArxShell } from './ui/ArxShell.vue'
export { default as AppFooter } from './ui/desktop/AppFooter.vue'
export { default as AppHeader } from './ui/desktop/AppHeader.vue'
export { default as AppSidebar } from './ui/desktop/AppSidebar.vue'
export { default as DesktopLayout } from './ui/desktop/DesktopLayout.vue'
export type { AppSidebarProps, SidebarItem } from './ui/desktop/types'
export type { FooterItem, HeaderItem, ShellItem } from './ui/extension'
export { ShellExtension } from './ui/extension'
export { default as MiniAppShell } from './ui/MiniAppShell.vue'
export { ShellPlugin } from './ui/plugin'
export { RAIL_MAX, RAIL_MIN, useRailWidth } from './ui/use-rail-width'
