export { default as AboutSettingsPage } from './ui/AboutSettingsPage.vue'
export type { FooterItem, HeaderItem, MobileTab, ShellItem } from './ui/extension'
export { ShellExtension } from './ui/extension'
export { default as MiniAppShell } from './ui/MiniAppShell.vue'
export { ShellPlugin } from './ui/plugin'
export type { SidebarItem } from './ui/types'
export { RAIL_MAX, RAIL_MIN, useRailWidth } from './ui/use-rail-width'
